version: '2'
services:
  rpi-climate-monitor-measurer:
    build: ./rpi-climate-monitor-measurer
    container_name: rpi-climate-monitor-measurer
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/mem:/dev/mem
    environment:
      DB_USER: dev
      DB_PASSWORD: 123456
      DB_LOCATION: /data/measurings.db   
  webserver:
    image: lispmeister/rpi-nginx
    container_name: rpi-climate-monitor-webserver
    ports:
      - "8000:80"
    environment:
      DB_USER: dev
      DB_PASSWORD: 123456
      DB_LOCATION: /data/measurings.db 