version: '2'
services:
  rpi-climate-monitor-measurer:
    build: ./rpi-climate-monitor-measurer
    container_name: rpi-climate-monitor-measurer
    links:
      - db
    depends_on:
      - db
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/mem:/dev/mem
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: measurings   
  webserver:
    image: lispmeister/rpi-nginx
    container_name: rpi-climate-monitor-webserver
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:80"
  db:
    build: ./rpi-climate-monitor-db
    container_name: rpi-climate-monitor-db
    ports:
      - "3306:3306"
    volumes: 
      - /var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: measurings